In [1]:
import torch

In [7]:
data_list = [[1,2], [3,4]]

tensor = torch.tensor(data_list)

print(tensor)
print(f'data type: {type(tensor)}')
print(f'dtype: {tensor.dtype}')
print(f'n of dimension: {tensor.ndim}')
print(f'shape: {tensor.shape}')
print(f'size: {tensor.size()}')

tensor([[1, 2],
        [3, 4]])
data type: <class 'torch.Tensor'>
dtype: torch.int64
n of dimension: 2
shape: torch.Size([2, 2])
size: torch.Size([2, 2])


In [10]:
import numpy as np

data_np = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

tensor_np = torch.tensor(data_np)
tensor_np


tensor([[1, 2],
        [3, 4]])

In [11]:
tensor_np = torch.from_numpy(data_np)
tensor_np

tensor([[1, 2],
        [3, 4]])

In [12]:
zero_frame = torch.zeros(2,3)
one_frame = torch.ones(2,3)
ordered_values = torch.arange(0,6,2)
uniform_samples = torch.rand(2,3)
std_uniform_samples = torch.randn(2,3)

print(zero_frame)
print(one_frame)
print(ordered_values)
print(uniform_samples)
print(std_uniform_samples)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 2, 4])
tensor([[0.7377, 0.8239, 0.9957],
        [0.7394, 0.5092, 0.9009]])
tensor([[ 0.7629, -0.8113,  2.2171],
        [ 0.2728,  0.8678,  0.1193]])


### 짧은 실습 · 습도만 선택하기

**목적**: axis 의미를 이용해 slicing함.

`weather`에서 모든 관측의 습도만 선택하고 shape를 확인함.


In [14]:
weather = torch.tensor([
    [18.0, 45.0, 0.0],
    [21.0, 55.0, 1.0],
    [25.0, 60.0, 1.0],
    [20.0, 50.0, 0.0],
])
feature_names = ["온도", "습도", "비 여부"]
print(weather)
print("shape:", tuple(weather.shape))

tensor([[18., 45.,  0.],
        [21., 55.,  1.],
        [25., 60.,  1.],
        [20., 50.,  0.]])
shape: (4, 3)


In [25]:
only_humidity = weather[:, 1]
print(only_humidity)
print('shape: ', tuple(only_humidity.shape))

tensor([45., 55., 60., 50.])
shape:  (4,)


### 짧은 실습 · shape guard 통과시키기

아래 `target_attempt`을 수정해 prediction과 같은 shape로 만듦. 실행 결과가 `안전한 1:1 비교 준비됨`이 되면 완료함.

In [35]:
prediction_column = torch.tensor([[2.0], [4.0], [6.0], [8.0]]) # [4,1]
target_flat = torch.tensor([3.0, 5.0, 7.0, 9.0]) # [4]

print(f"prediction_column shape: {prediction_column.shape}")
print(f"target_flat shape: {target_flat.shape}")

# 1번 인덱스에 차원을 추가: [4] -> [4,1] 
target_attempt = target_flat.unsqueeze(1) # [4,1]

print(f"target_attempt shape: {target_attempt.shape}")

if target_attempt.shape == prediction_column.shape:
    print("안전한 1:1 비교 준비됨")
else:
    print("shape를 다시 확인함:", tuple(prediction_column.shape), tuple(target_attempt.shape))

prediction_column shape: torch.Size([4, 1])
target_flat shape: torch.Size([4])
target_attempt shape: torch.Size([4, 1])
안전한 1:1 비교 준비됨
