In [1]:
import numpy as np

In [5]:
regions = np.array(["서울", "부산", "대전"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4"])
sales = np.array([
    [10, 12, 14, 16],
    [20, 18, 21, 25],
    [11, 13, 15, 17],
])

print("지역:", regions)
print("분기:", quarters)
print("매출표:\n", sales)
print("shape:", sales.shape)

지역: ['서울' '부산' '대전']
분기: ['Q1' 'Q2' 'Q3' 'Q4']
매출표:
 [[10 12 14 16]
 [20 18 21 25]
 [11 13 15 17]]
shape: (3, 4)


In [27]:
print("부산·대전의 Q2~Q4:\n", sales[1:3, 1:5])
print("모든 지역의 Q2~Q3:\n", sales[:, 1:4])
print("서울의 모든 분기:\n", sales[0, :])

부산·대전의 Q2~Q4:
 [[18 21 25]
 [13 15 17]]
모든 지역의 Q2~Q3:
 [[12 14 16]
 [18 21 25]
 [13 15 17]]
서울의 모든 분기:
 [10 12 14 16]


In [ ]:
# TODO array[n:m, x:y] VS array[n:m][x:y] 정리하기
# sales[1:3, 1:5] # 맞는 접근
sales[1:3][1:5] # 틀린 접근
sales[1:3]

array([[20, 18, 21, 25],
       [11, 13, 15, 17]])

In [29]:
years = np.arange(2010, 2020)
gdp = np.array([6610, 7637, 8127, 8885, 10385,
                12565, 14403, 12398, 8282, 10672])

In [30]:
over_10000 = gdp > 10000

print("GDP:", gdp)
print("조건:", over_10000)
print("조건 dtype:", over_10000.dtype)
print("같은 shape:", gdp.shape == over_10000.shape)

GDP: [ 6610  7637  8127  8885 10385 12565 14403 12398  8282 10672]
조건: [False False False False  True  True  True  True False  True]
조건 dtype: bool
같은 shape: True


In [ ]:
mask = gdp > 10000


print("8,000 이상 10,000 이하:", gdp >= 8000 and gdp <= 10000)
print("8,000 미만 또는 12,000 초과:", (gdp < 8000) + (gdp > 12000))

In [ ]:
# TODO: numpy array에서 논리연산자, 산술연산자의 구현과 용례!

print("8000 이상: ", gdp >= 8000)
print("10000 이하: ", gdp <= 10000)
print("8000 이상 AND 10,000 이하: ", (gdp >= 8000) * (gdp <= 10000)) # *
print("8000 이상 AND 10,000 이하: ", (gdp >= 8000) & (gdp <= 10000)) # AND

or_more_than_8000 = gdp[gdp >= 8000]
or_less_than_10000 = gdp[gdp <= 10000]
or_more_than_8000_and_or_less_than_10000 = gdp[(gdp >= 8000) * (gdp <= 10000)]
print("8000 이상 AND 10,000 이하(masked): ", or_more_than_8000_and_or_less_than_10000)
print("------------------------------------------------------------------------")
print("8000 미만: ", gdp < 8000)
print("10000 초과: ", gdp > 10000)
print("8000 미만 OR 12,000 초과: ", (gdp < 8000) + (gdp > 12000)) # +
print("8000 미만 OR 12,000 초과: ", (gdp < 8000) | (gdp > 12000)) # OR

less_than_8000_or_over_than_120000 = gdp[(gdp < 8000) + (gdp > 12000)]
print("8000 미만 OR 12,000 초과(masked): ", less_than_8000_or_over_than_120000)

8000 이상:  [False False  True  True  True  True  True  True  True  True]
10000 이하:  [ True  True  True  True False False False False  True False]
8000 이상 AND 10,000 이하:  [False False  True  True False False False False  True False]
8000 이상 AND 10,000 이하(masked):  [8127 8885 8282]
------------------------------------------------------------------------
8000 미만:  [ True  True False False False False False False False False]
10000 초과:  [False False False False  True  True  True  True False  True]
8000 미만 OR 12,000 초과:  [ True  True False False False  True  True  True False False]
8000 미만 OR 12,000 초과(masked):  [ 6610  7637 12565 14403 12398]


1부터 100까지의 정수에서 짝수만 선택합니다.

설계 질문:

1. 1부터 100까지 만들 `arange`의 stop은? -> 101
2. 짝수는 2로 나눈 나머지가 무엇인가?       -> 0
3. 조건 결과를 배열 대괄호 어디에 넣는가?     -> 안에

In [58]:
numbers = np.arange(1,101)

mask = numbers % 2 == 0

odds = numbers[mask]

print("numbers:\n", numbers.reshape(10,10))
print("odd numbers:\n", odds.reshape(5,10))


numbers:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
odd numbers:
 [[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


## Fancy Indexing

In [67]:
og = np.arange(0,101, dtype=int)

print(og)

# 추출하고자 하는 인덱스를 배열로 전달해 인덱싱할 수 있다.
print(og[[0,2,4]])

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[0 2 4]


## 정렬: sort VS sorted

In [68]:
one_to_hundred = og.copy()

sorted(one_to_hundred)


[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(44),
 np.int64(45),
 np.int64(46),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(52),
 np.int64(53),
 np.int64(54),
 np.int64(55),
 np.int64(56),
 np.int64(57),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(62),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.i

## Axis

- axis=0: 열 기준
- axis=1: 행 기준
